### ISSUE TITLE
Misuse "sudo" leads to happen error during running gateway-server.js

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/SmartHome-Demo#188]
## Description:

Due to misuse "sudo" command in the [README.md](https://github.com/01org/SmartHome-Demo/tree/master/gateway#native-installation) to install lib package(iot-rest-api-server), error happens when running gateway-server.js.

## Steps:
1. Clone smartHome-demo
```
$ cd /opt
$ sudo git clone https://github.com/01org/SmartHome-Demo
$ cd SmartHome-Demo
```
2. Install node.js dependencies
```
$ cd /opt/SmartHome-Demo
$ sudo npm install iot-rest-api-server express websocket
$ sudo npm install mraa #optional
```
3.Start the Home GW services
```
$ cd /opt/SmartHome-Demo
$ /usr/bin/node gateway/gateway-server.js & # Start server with 3D UI and rules engine.
```

## Actual Result:
![selection_001](https://user-images.githubusercontent.com/17694094/32478471-f53b8712-c3bf-11e7-8858-f17f4b847b0a.png)

## Expect Result:
Home GW service starts successfully and no error popups

## Comment
This issue hasn't relative with node version and current node version is 6.11.0. 
It will popups error when node version is 7.*.* , 8.*.* or 9.*.*
![capture](https://user-images.githubusercontent.com/17694094/32479023-e4c00e00-c3c2-11e7-81b4-370af6d0016a.PNG)

## Proposal:

Remove 'sudo' and these commands are used under the ordinary user.
e.g.
```
$ sudo git clone https://github.com/01org/SmartHome-Demo
$ sudo npm install iot-rest-api-server express websocket
$ sudo npm install mraa #optional
```

modify to 
```
$ git clone https://github.com/01org/SmartHome-Demo
$ npm install iot-rest-api-server express websocket
$ npm install mraa #optional
```

**Comment by gvancuts** [comment]
Hi @xiaoyu3x , thanks for the report! I have created a PR to fix this (I have not tested it however). Could you test that PR and let me know if it properly fixes this issue? Thanks!

**Comment by xiaoyu3x** [comment]
OK, @gvancuts 
I will verify PR #189  and add comment into it.

**Comment by xiaoyu3x** [comment]
This issue isn't reproduced with commit [c791f25](https://github.com/intel/SmartHome-Demo/commit/c791f257d03148bbd837ef4aecc173b339685d79)
