### ISSUE TITLE
Can't find module 'arduino101_pins' when running multiserver2.js

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/SmartHome-Demo#191]
## Description:

'arduino101_pins' module has been abandoned, so need to update multiserver2.js code.

## Steps:
1.Build the  [multiserver2.js](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/multiserver2.js) and flash it  into A101.
2.Reset it and check output by `minicom -D /dev/ttyUSB0`
![selection_046](https://user-images.githubusercontent.com/17694094/35319947-f7893786-011c-11e8-8c3f-26422eb0e38c.png)

## Actual Result:
No module 'arduino101_pins'

## Expect Result:
No error outputs

## Comment:
There is the same issue  when building multiserver.js.

**Comment by xiaoyu3x** [comment]
To resolve this issue, PR #192 has been submitted.
Please help to merge.

**Comment by ttzeng** [comment]
@xiaoyu3x thanks for updating the code with the the latest API. Though I don't have the hardware setup for verification, but the patch looks good. Thanks.

**Comment by xiaoyu3x** [comment]
#192 has been merged, so closed it.

**Comment by uhofemei** [comment]
@xiaoyu3x which version of Zephyr are you testing this with? I received an update from one of our ZJS developers stating that Bluetooth in Zephyr version 1.10 should be more stable. Would you have cycles to test this? https://github.com/intel/zephyr.js/issues/1237#issuecomment-360563217

**Comment by jimmy-huang** [comment]
@uhofemei Yeah, so looking at the report, it looks like all the tests on A101 passed, except the ones blocked by the cloud portal issue.

**Comment by uhofemei** [comment]
We have a team in PRC testing the ZJS multiserver2.js example. I asked them if they would be able to pick up Zephyr 1.10 to try this out. Thanks.
